version: "3"

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=gateway
    volumes:
      - .:/app
    environment:
      - SERVICE_NAME=gateway
    env_file:
      - .env
    depends_on:
      - auth-service
      - profile-service
      - rabbitmq
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=auth-service
    volumes:
      - .:/app
    environment:
      - SERVICE_NAME=auth-service
    env_file:
      - .env
    depends_on:
      - db-auth
      - rabbitmq
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    networks:
      - backend

  profile-service:
    build:
      context: ./profile-service
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=profile-service
    volumes:
      - .:/app
    environment:
      - SERVICE_NAME=profile-service
    env_file:
      - .env
    depends_on:
      - db-profile
      - rabbitmq
    ports:
      - ${PROFILE_PORT}:${PROFILE_PORT}
    networks:
      - backend

  db-auth:
    image: postgres
    environment:
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_HOST=${AUTH_POSTGRES_HOST}
    env_file:
      - .env
    command: -p ${AUTH_POSTGRES_PORT}
    volumes:
      - auth-db:/var/lib/postgresql/data
    expose:
      - ${AUTH_POSTGRES_PORT}
    ports:
      - 5434:${AUTH_POSTGRES_PORT}
    networks:
      backend:
        ipv4_address: ${AUTH_POSTGRES_HOST}

  db-profile:
    image: postgres
    environment:
      - POSTGRES_DB=${PROFILE_POSTGRES_DB}
      - POSTGRES_USER=${PROFILE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PROFILE_POSTGRES_PASSWORD}
      - POSTGRES_HOST=${PROFILE_POSTGRES_HOST}
    env_file:
      - .env
    command: -p ${PROFILE_POSTGRES_PORT}
    volumes:
      - profile-db:/var/lib/postgresql/data
    expose:
      - ${PROFILE_POSTGRES_PORT}
    ports:
      - ${PROFILE_POSTGRES_PORT}:${PROFILE_POSTGRES_PORT}
    networks:
      backend:
        ipv4_address: ${PROFILE_POSTGRES_HOST}

  rabbitmq:
    image: rabbitmq:management-alpine
    env_file:
      - .env
    expose:
      - ${RABBITMQ_PORT}
    ports:
      - ${RABBITMQ_MANAGEMENT_UI_PORT}:${RABBITMQ_MANAGEMENT_UI_PORT}
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    networks:
      backend:
        ipv4_address: ${RABBITMQ_HOST}

volumes:
  auth-db:
  profile-db:
