FROM node:18-alpine As base

WORKDIR /usr/src/app

RUN chown -R node:node /usr/src/app

RUN echo https://mirror.yandex.ru/mirrors/alpine/v3.17/main/x86_64/ \
  && apk add --no-cache --virtual build-dependencies \
  python3 make g++ \